version: '2'

services:

    tsf_customer_management_db:
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: defaultdb
            MYSQL_USER: defaultdbuser
            MYSQL_PASSWORD: defaultdbpasswd

    tsf_customer_management_web:
        volumes:
            - ../:/var/www/html:cached

#volumes:
    #tsf_customer_management_sync:
        #external: true
