version: '2'

services:

    tsf_customer_management_db:
        container_name: tsf_customer_management_db
        image: mysql:5.7.11
        ports:
            - "3306:3306"
        volumes:
            - ./db/mysql:/var/lib/mysql:cached
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: defaultdb
            MYSQL_USER: defaultdbuser
            MYSQL_PASSWORD: defaultdbpasswd

    tsf_customer_management_web:
        container_name: tsf_customer_management_web
        build: ./web
        ports:
            - "8000:80"
        volumes:
            - ../:/var/www/html:cached
        links:
            - tsf_customer_management_db:db

    tsf_customer_management_pma:
        container_name: tsf_customer_management_pma
        image: phpmyadmin/phpmyadmin:4.5.3.1-1
        ports:
            - "8080:8080"
        links:
            - tsf_customer_management_db:db
